import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import MainLayout from "./components/templates/MainLayout";
import SectionBorder from "./components/molecules/SectionBorder";

import LightRays from "./components/molecules/LightRay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-poppins antialiased relative min-h-screen bg-linear-to-b from-black via-[#002520] to-[#006154]`}>
        <div className="absolute z-0 top-0 left-0 w-full h-full">
          <LightRays
            raysOrigin="top-center"
            raysColor="#00ffff"
            raysSpeed={1.5}
            lightSpread={0.8}
            rayLength={1.2}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0.05}
            className="custom-rays"
          />
        </div>
        <MainLayout>
          <section className="z-10 w-full h-screen lg:pt-20 lg:pb-10 pb-4 pt-13 px-4 lg:px-10 mx-auto">
            <SectionBorder className="w-full h-full">{children}</SectionBorder>
          </section>
        </MainLayout>
      </body>
    </html>
  );
}
